// <auto-generated />
using System;
using EcgMonitor.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EcgMonitor.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260509092619_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EcgMonitor.API.Models.DoctorReview", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AgreedWithAi")
                        .HasColumnType("boolean");

                    b.Property<string>("Diagnosis")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DoctorName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("EcgRecordId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EcgRecordId")
                        .IsUnique();

                    b.ToTable("DoctorReviews");
                });

            modelBuilder.Entity("EcgMonitor.API.Models.EcgRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double?>("AiConfidence")
                        .HasColumnType("double precision");

                    b.Property<string>("AiDiagnosis")
                        .HasColumnType("text");

                    b.Property<string>("AiReasoning")
                        .HasColumnType("text");

                    b.Property<string>("AiUrgency")
                        .HasColumnType("text");

                    b.Property<double[]>("DataPoints")
                        .IsRequired()
                        .HasColumnType("double precision[]");

                    b.Property<double>("HeartRateBpm")
                        .HasColumnType("double precision");

                    b.Property<bool>("IsAnomaly")
                        .HasColumnType("boolean");

                    b.Property<string>("PatientId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SampleRateHz")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("EcgRecords");
                });

            modelBuilder.Entity("EcgMonitor.API.Models.DoctorReview", b =>
                {
                    b.HasOne("EcgMonitor.API.Models.EcgRecord", "EcgRecord")
                        .WithOne("Review")
                        .HasForeignKey("EcgMonitor.API.Models.DoctorReview", "EcgRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EcgRecord");
                });

            modelBuilder.Entity("EcgMonitor.API.Models.EcgRecord", b =>
                {
                    b.Navigation("Review");
                });
#pragma warning restore 612, 618
        }
    }
}
